version: '3.1'
services:
  db:
    image: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=microservices_blinkdev
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - microservices_blinkdev:/var/lib/mysql

volumes:
  microservices_blinkdev: